name: 'Go Code Coverage to Prometheus'
description: 'Calculates and pushes Go code coverage to Prometheus'
icon: check-square
inputs:
  prometheus_endpoint:
    description: 'The Prometheus Pushgateway endpoint'
    required: true
  labels:
    description: 'Additional labels to add to the metric (e.g., "env=prod,region=us-east-1")'
    required: false
runs:
  using: 'node24'
  main: 'dist/index.js' 
