name: Coverage Publisher Example

on: [workflow_dispatch]

jobs:
  test-and-push-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.25'

      - name: Load coverage from previous action step
        run: cat coverage.txt

      - name: Push coverage to prometheus
        uses: ./
        with:
          prometheus_endpoint: http://pushgateway.dev-cyderes.io
          labels: branch=${{ github.ref_name }}
